### ISSUE TITLE
Enum:  Value1 is already defined as value Value1

### ISSUE THREAD

**Issue by pocman** [zalando/api-first-hand#12]
Hi,

I'm trying to define two properties, each with an enumeration containing an equal value.

```
definitions:
  Transition:
    type: object
    properties:
      trigger_state_value:
        type: string
        enum: ["completed","canceled"]
      child_state_value:
        type: string
        enum: ["canceled"]
```

I have this error `Canceled is already defined as value Canceled; val Canceled = StateValueOpt("canceled")` which makes sense considering the generated code.

You should probably change the val name generator.
