### ISSUE TITLE
Number parsing

### ISSUE THREAD

**Issue by pocman** [zalando/api-first-hand#20]
I have this issue : 
parsing default `0` value into a `type: number, format: double`.
`<p id="detail" class="pre">[ClassCastException: java.lang.Integer cannot be cast to java.lang.Double]</p>`

parsing default `3.3` value into a `type: number, format: float`.
`<p id="detail" class="pre">[ClassCastException: java.lang.Double cannot be cast to java.lang.Float]</p>`

With
```
  geometry:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: number
            format: double
            example: [4.49965, 52.06891]
```
parsing in a post body : 
```
      "coordinates": [
        [
          4.49965,
          52.06891
        ]
      ]
```
Returns 
`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to java.lang.Double]]`

![capture d ecran 2016-07-25 a 15 51 29](https://cloud.githubusercontent.com/assets/1695808/17103664/b64636cc-527f-11e6-894c-18729396c460.png)
