### ISSUE TITLE
OperationId required to generate lowerCamelCased action names

### ISSUE THREAD

**Issue by pocman** [zalando/api-first-hand#24]
```
paths:
  /options:
    post:
      operationId: postOptions
```
will generate `val postOptions = postOptionsAction{}`

```
paths:
  /options:
    post:
```
will generate `val postoptions = postoptionsAction{}`

Action name generator should create valid lowerCamelCased action names.
