### ISSUE TITLE
Required properties validation

### ISSUE THREAD

**Issue by sergey-novikov** [zalando/api-first-hand#60]
Endpoint:
```
parameters:
  - name: query
    in: body
    required: true
    schema:
      "$ref": "#/definitions/Query"
```

definition:
```
  Query:
    type: object
    required:
      - language
    properties:
      language:
        type: string
```

request body:
```
{
}
```

Expected result: validation error (`language` property is required)
Actual result: no errors
